import { useCallback, useEffect, useMemo, useState } from 'react';
import './admin.css';

const API = import.meta.env.VITE_API_BASE_URL || 'https://sites-maker-3bkh.onrender.com';
const TOKEN_KEY = 'wm_admin_token';

const statusMeta = {
  new: ['New', 'violet'], contacted: ['Contacted', 'blue'], 'in-progress': ['In progress', 'gold'], completed: ['Completed', 'green'], archived: ['Archived', 'gray']
};
const priorityMeta = { low: 'Low', normal: 'Normal', high: 'High', urgent: 'Urgent' };

function moneyDate(value) {
  if (!value) return '—';
  return new Intl.DateTimeFormat('en-IN', { day:'2-digit', month:'short', year:'numeric', hour:'2-digit', minute:'2-digit' }).format(new Date(value));
}

function Badge({ type='status', value }) {
  const label = type === 'status' ? statusMeta[value]?.[0] || value : priorityMeta[value] || value;
  const tone = type === 'status' ? statusMeta[value]?.[1] || 'gray' : value === 'urgent' ? 'red' : value === 'high' ? 'gold' : value === 'normal' ? 'blue' : 'gray';
  return <span className={`badge ${tone}`}><i />{label}</span>;
}

function Login({ onLogin }) {
  const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [busy,setBusy]=useState(false); const [error,setError]=useState('');
  const submit=async e=>{e.preventDefault();setBusy(true);setError('');try{const r=await fetch(`${API}/api/inquiries/admin/login`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,password})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Login failed');sessionStorage.setItem(TOKEN_KEY,d.token);onLogin(d.token)}catch(err){setError(err.message)}finally{setBusy(false)}};
  return <div className="admin-auth"><div className="auth-orb orb-one"/><div className="auth-orb orb-two"/><div className="login-card"><div className="brand-mark"><span>W</span><div><b>Website</b> <em>Makers</em><small>ADMIN CONSOLE</small></div></div><div className="login-copy"><span className="eyebrow">Private workspace</span><h1>Welcome back.</h1><p>Manage enquiries, follow-ups and customer conversations from one command center.</p></div><form onSubmit={submit}><label>Admin email<input type="email" autoComplete="username" value={email} onChange={e=>setEmail(e.target.value)} placeholder="admin@yourdomain.com" required/></label><label>Password<input type="password" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="••••••••••••" required/></label>{error&&<div className="auth-error">{error}</div>}<button className="primary-btn" disabled={busy}>{busy?'Authenticating…':'Enter command center'} <span>↗</span></button></form><div className="secure-line"><span>⌁</span> Protected session · 8 hour token</div></div></div>;
}

export default function AdminApp(){
  const [token,setToken]=useState(()=>sessionStorage.getItem(TOKEN_KEY));
  const [inquiries,setInquiries]=useState([]); const [stats,setStats]=useState({total:0,new:0,contacted:0,inProgress:0,completed:0});
  const [loading,setLoading]=useState(false); const [error,setError]=useState(''); const [query,setQuery]=useState(''); const [status,setStatus]=useState(''); const [priority,setPriority]=useState(''); const [selected,setSelected]=useState(null); const [replyOpen,setReplyOpen]=useState(false); const [lastSync,setLastSync]=useState(null);

  const headers=useMemo(()=>({Authorization:`Bearer ${token}`}),[token]);
  const logout=()=>{sessionStorage.removeItem(TOKEN_KEY);setToken(null)};
  const load=useCallback(async()=>{if(!token)return;setLoading(true);setError('');try{const params=new URLSearchParams();if(query)params.set('q',query);if(status)params.set('status',status);if(priority)params.set('priority',priority);params.set('limit','100');const r=await fetch(`${API}/api/inquiries?${params}`,{headers});const d=await r.json();if(r.status===401){logout();return}if(!r.ok)throw new Error(d.error||'Could not load inquiries');setInquiries(d.data||[]);setStats(d.stats||{});setLastSync(new Date())}catch(e){setError(e.message)}finally{setLoading(false)}},[token,query,status,priority]);
  useEffect(()=>{load()},[load]);
  useEffect(()=>{const id=setInterval(load,30000);return()=>clearInterval(id)},[load]);

  const update=async(id,payload)=>{const r=await fetch(`${API}/api/inquiries/${id}`,{method:'PATCH',headers:{...headers,'Content-Type':'application/json'},body:JSON.stringify(payload)});const d=await r.json();if(!r.ok)throw new Error(d.error||'Update failed');setSelected(d.data);setInquiries(x=>x.map(i=>i._id===id?d.data:i));return d.data};
  const exportCsv=()=>{const rows=[['Name','Email','Phone','Service','Status','Priority','Created'],...inquiries.map(i=>[i.name,i.email,i.phone,i.service,i.status,i.priority,i.createdAt])];const csv=rows.map(r=>r.map(v=>`"${String(v??'').replaceAll('"','""')}"`).join(',')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download=`website-makers-inquiries-${new Date().toISOString().slice(0,10)}.csv`;a.click();URL.revokeObjectURL(a.href)};

  if(!token)return <Login onLogin={setToken}/>;
  return <div className="admin-shell">
    <aside className="sidebar"><div className="brand-mark side"><span>W</span><div><b>Website</b> <em>Makers</em><small>ADMIN CONSOLE</small></div></div><nav><a className="active"><span>⌂</span> Overview</a><a><span>◈</span> Inquiries <b>{stats.new||0}</b></a><a><span>◎</span> Customers</a><a><span>◌</span> Analytics</a><a><span>☆</span> Reviews</a></nav><div className="side-bottom"><div className="health"><i/> API online<div><small>MongoDB connected</small><strong>Healthy</strong></div></div><button onClick={logout} className="logout">↪ Sign out</button></div></aside>
    <main className="admin-main"><header className="topbar"><div><span className="eyebrow">Command center</span><h1>Good to see you.</h1></div><div className="top-actions"><div className="live-status"><i/> Live <small>{lastSync?`Synced ${lastSync.toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}`:'Syncing'}</small></div><button className="icon-btn" onClick={load} title="Refresh">↻</button><button className="export-btn" onClick={exportCsv}>↓ Export CSV</button></div></header>
      <section className="stat-grid"><Stat label="Total enquiries" value={stats.total||0} icon="◈" trend="All time"/><Stat label="New leads" value={stats.new||0} icon="✦" tone="violet" trend="Need attention"/><Stat label="In progress" value={stats.inProgress||0} icon="⌁" tone="gold" trend="Active pipeline"/><Stat label="Completed" value={stats.completed||0} icon="✓" tone="green" trend="Closed wins"/></section>
      <section className="workspace-card"><div className="workspace-head"><div><h2>Customer enquiries</h2><p>Every lead, one place. No spreadsheet archaeology required.</p></div><div className="filters"><div className="search"><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search name, email, service…"/></div><select value={status} onChange={e=>setStatus(e.target.value)}><option value="">All statuses</option>{Object.entries(statusMeta).map(([v,[l]])=><option key={v} value={v}>{l}</option>)}</select><select value={priority} onChange={e=>setPriority(e.target.value)}><option value="">All priorities</option>{Object.keys(priorityMeta).map(v=><option key={v} value={v}>{priorityMeta[v]}</option>)}</select></div></div>{error&&<div className="panel-error">{error}</div>}<div className="table-wrap"><table><thead><tr><th>Customer</th><th>Service</th><th>Status</th><th>Priority</th><th>Received</th><th></th></tr></thead><tbody>{loading&&!inquiries.length?<tr><td colSpan="6"><div className="loading"><span/> Loading enquiries…</div></td></tr>:inquiries.length?inquiries.map(i=><tr key={i._id} onClick={()=>setSelected(i)} className={selected?._id===i._id?'selected':''}><td><div className="customer-cell"><div className="avatar">{i.name?.slice(0,1).toUpperCase()}</div><div><strong>{i.name}</strong><small>{i.email}</small></div></div></td><td><span className="service-pill">{i.service||'Other'}</span></td><td><Badge value={i.status}/></td><td><Badge type="priority" value={i.priority||'normal'}/></td><td className="date">{moneyDate(i.createdAt)}</td><td><button className="row-arrow" onClick={e=>{e.stopPropagation();setSelected(i)}}>→</button></td></tr>):<tr><td colSpan="6"><div className="empty"><div>◇</div><h3>No enquiries found</h3><p>Try changing the filters or wait for the next customer.</p></div></td></tr>}</tbody></table></div></section>
    </main>
    {selected&&<DetailDrawer inquiry={selected} onClose={()=>setSelected(null)} onUpdate={update} onReply={()=>setReplyOpen(true)}/>} {replyOpen&&selected&&<ReplyModal inquiry={selected} token={token} onClose={()=>setReplyOpen(false)} onSent={d=>{setSelected(d);setInquiries(x=>x.map(i=>i._id===d._id?d:i));setReplyOpen(false)}}/>}
  </div>;
}

function Stat({label,value,icon,trend,tone=''}){return <div className={`stat-card ${tone}`}><div className="stat-icon">{icon}</div><div><span>{label}</span><strong>{value}</strong><small>{trend}</small></div><div className="spark"><i/><i/><i/><i/><i/></div></div>}
function DetailDrawer({inquiry,onClose,onUpdate,onReply}){const [notes,setNotes]=useState(inquiry.adminNotes||'');const [saving,setSaving]=useState(false);useEffect(()=>setNotes(inquiry.adminNotes||''),[inquiry._id,inquiry.adminNotes]);const save=async()=>{setSaving(true);try{await onUpdate(inquiry._id,{adminNotes:notes})}finally{setSaving(false)}};return <div className="drawer-layer"><div className="drawer-backdrop" onClick={onClose}/><aside className="drawer"><div className="drawer-head"><div><span className="eyebrow">Inquiry #{String(inquiry._id).slice(-6).toUpperCase()}</span><h2>{inquiry.name}</h2><p>{inquiry.email}</p></div><button className="icon-btn" onClick={onClose}>×</button></div><div className="drawer-actions"><button className="primary-btn small" onClick={onReply}>↗ Respond</button><a className="secondary-btn" href={`tel:${inquiry.phone}`}>☎ Call</a><a className="secondary-btn" href={`https://wa.me/${inquiry.phone.replace(/\D/g,'')}`} target="_blank" rel="noreferrer">WhatsApp</a></div><div className="drawer-section"><label>Status</label><div className="segmented">{Object.entries(statusMeta).map(([v,[l]])=><button key={v} className={inquiry.status===v?'active':''} onClick={()=>onUpdate(inquiry._id,{status:v})}>{l}</button>)}</div></div><div className="drawer-section two"><div><label>Priority</label><select value={inquiry.priority||'normal'} onChange={e=>onUpdate(inquiry._id,{priority:e.target.value})}>{Object.keys(priorityMeta).map(v=><option key={v}>{v}</option>)}</select></div><div><label>Service</label><div className="read-field">{inquiry.service||'Other'}</div></div></div><div className="message-box"><label>Customer message</label><p>{inquiry.message||'No message supplied.'}</p></div><div className="drawer-section"><label>Private notes</label><textarea value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Add follow-up notes, budget, requirements…"/><button className="save-note" onClick={save} disabled={saving}>{saving?'Saving…':'Save notes'}</button></div>{inquiry.responses?.length>0&&<div className="timeline"><label>Conversation</label>{inquiry.responses.map((r,idx)=><div className="timeline-item" key={idx}><i/><div><small>{moneyDate(r.sentAt)} · {r.channel}</small><p>{r.message}</p></div></div>)}</div>}<div className="drawer-footer"><span>Received {moneyDate(inquiry.createdAt)}</span><span>{inquiry.phone}</span></div></aside></div>}
function ReplyModal({inquiry,token,onClose,onSent}){const [subject,setSubject]=useState(`Re: Your Website Makers enquiry`);const [message,setMessage]=useState(`Hi ${inquiry.name},\n\nThank you for reaching out to Website Makers.\n\n`);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const send=async()=>{if(!message.trim())return;setBusy(true);setError('');try{const r=await fetch(`${API}/api/inquiries/${inquiry._id}/respond`,{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify({subject,message})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Could not send reply');onSent(d.data)}catch(e){setError(e.message)}finally{setBusy(false)}};return <div className="modal-layer"><div className="modal-backdrop" onClick={onClose}/><div className="reply-modal"><div className="reply-head"><div><span className="eyebrow">Direct email</span><h2>Reply to {inquiry.name}</h2><p>{inquiry.email}</p></div><button className="icon-btn" onClick={onClose}>×</button></div><label>Subject<input value={subject} onChange={e=>setSubject(e.target.value)}/></label><label>Message<textarea rows="10" value={message} onChange={e=>setMessage(e.target.value)}/></label>{error&&<div className="panel-error">{error}</div>}<div className="reply-footer"><span>Sent through your configured SMTP account.</span><button className="primary-btn" onClick={send} disabled={busy}>{busy?'Sending…':'Send reply ↗'}</button></div></div></div>}
