import { useCallback, useEffect, useState } from 'react';
import './admin.css';

const API = (import.meta.env.VITE_API_BASE_URL || (import.meta.env.PROD ? 'https://website-makers-api.onrender.com' : 'http://localhost:4000')).replace(/\/$/, '');
const TOKEN_KEY = 'wm_admin_token';
const statusMeta = { new:['New','violet'], contacted:['Contacted','blue'], 'in-progress':['In progress','gold'], completed:['Completed','green'], archived:['Archived','gray'] };
const priorityMeta = { low:'Low', normal:'Normal', high:'High', urgent:'Urgent' };
const fmtDate = v => v ? new Intl.DateTimeFormat('en-IN',{day:'2-digit',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit'}).format(new Date(v)) : '—';
const money = n => new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(n);

function Badge({type='status',value}){const label=type==='status'?(statusMeta[value]?.[0]||value):(priorityMeta[value]||value);const tone=type==='status'?(statusMeta[value]?.[1]||'gray'):value==='urgent'?'red':value==='high'?'gold':value==='normal'?'blue':'gray';return <span className={`badge ${tone}`}><i/>{label}</span>}

async function api(path, options={}, token){
  const headers={...(options.body?{'Content-Type':'application/json'}:{}),...(token?{Authorization:`Bearer ${token}`}:{})};
  const r=await fetch(`${API}${path}`,{...options,headers});
  const d=await r.json().catch(()=>({}));
  if(r.status===401) throw Object.assign(new Error('Session expired. Please sign in again.'),{code:401});
  if(!r.ok) throw new Error(d.error||'Request failed.');
  return d;
}

function Login({onLogin}){const[email,setEmail]=useState(''),[password,setPassword]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');const submit=async e=>{e.preventDefault();setBusy(true);setError('');try{const d=await api('/api/inquiries/admin/login',{method:'POST',body:JSON.stringify({email,password})});sessionStorage.setItem(TOKEN_KEY,d.token);onLogin(d.token)}catch(err){setError(err.message)}finally{setBusy(false)}};return <div className="admin-auth"><div className="auth-orb orb-one"/><div className="auth-orb orb-two"/><div className="login-card"><div className="brand-mark"><img src="/assets/sites-maker-logo.webp" alt="Sites Maker" className="brand-logo"/><div><b>Sites</b> <em>Maker</em><small>ADMIN CONSOLE</small></div></div><div className="login-copy"><span className="eyebrow">Private workspace</span><h1>Welcome back.</h1><p>Leads, customers, quotes, reviews and analytics in one command center.</p></div><form onSubmit={submit}><label>Admin email<input type="email" autoComplete="username" value={email} onChange={e=>setEmail(e.target.value)} placeholder="admin@yourdomain.com" required/></label><label>Password<input type="password" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="••••••••••••" required/></label>{error&&<div className="auth-error">{error}</div>}<button className="primary-btn" disabled={busy}>{busy?'Authenticating…':'Enter command center'} <span>↗</span></button></form><div className="secure-line">⌁ Protected JWT session · 8 hours</div></div></div>}

export default function AdminApp(){
  const[token,setToken]=useState(()=>sessionStorage.getItem(TOKEN_KEY));
  const[tab,setTab]=useState('overview'); const[error,setError]=useState(''); const[toast,setToast]=useState('');
  const[inquiries,setInquiries]=useState([]); const[clients,setClients]=useState([]); const[stats,setStats]=useState({}); const[customers,setCustomers]=useState([]); const[reviews,setReviews]=useState([]); const[analytics,setAnalytics]=useState(null); const[selected,setSelected]=useState(null); const[replyOpen,setReplyOpen]=useState(false); const[quoteOpen,setQuoteOpen]=useState(false); const[loading,setLoading]=useState(false); const[query,setQuery]=useState(''); const[status,setStatus]=useState(''); const[priority,setPriority]=useState(''); const[lastSync,setLastSync]=useState(null);
  const logout=()=>{sessionStorage.removeItem(TOKEN_KEY);setToken(null)};
  const loadInquiries=useCallback(async()=>{if(!token)return;setLoading(true);try{const p=new URLSearchParams({limit:'100'});if(query)p.set('q',query);if(status)p.set('status',status);if(priority)p.set('priority',priority);const d=await api(`/api/inquiries?${p}`,{},token);setInquiries(d.data||[]);setStats(d.stats||{});setLastSync(new Date())}catch(e){if(e.code===401)logout();else setError(e.message)}finally{setLoading(false)}},[token,query,status,priority]);
  const loadExtra=useCallback(async()=>{if(!token)return;const requests=[['customers','/api/inquiries/admin/customers'],['reviews','/api/reviews/admin'],['analytics','/api/analytics/admin/summary'],['clients','/api/clients/admin']];try{const results=await Promise.all(requests.map(async([name,path])=>{try{return [name,await api(path,{},token),null]}catch(e){return [name,null,e]}}));for(const [name,data,error] of results){if(error){if(error.code===401){logout();return}setError(`${name[0].toUpperCase()+name.slice(1)}: ${error.message}`);continue}if(name==='customers')setCustomers(data?.data||[]);if(name==='reviews')setReviews(data?.data||[]);if(name==='analytics')setAnalytics(data?.data||null);if(name==='clients')setClients(data?.data||[])}}catch(e){if(e.code===401)logout();else setError(e.message)}},[token]);
  useEffect(()=>{loadInquiries();loadExtra()},[loadInquiries,loadExtra]);
  useEffect(()=>{const id=setInterval(()=>{loadInquiries();loadExtra()},30000);return()=>clearInterval(id)},[loadInquiries,loadExtra]);
  useEffect(()=>{if(toast){const t=setTimeout(()=>setToast(''),3200);return()=>clearTimeout(t)}},[toast]);
  if(!token)return <Login onLogin={setToken}/>;
  const update=async(id,payload)=>{const d=await api(`/api/inquiries/${id}`,{method:'PATCH',body:JSON.stringify(payload)},token);setSelected(d.data);setInquiries(x=>x.map(i=>i._id===id?d.data:i));setToast('Inquiry updated');return d.data};
  const remove=async(id)=>{if(!confirm('Delete this inquiry permanently?'))return;await api(`/api/inquiries/${id}`,{method:'DELETE'},token);setSelected(null);setInquiries(x=>x.filter(i=>i._id!==id));setToast('Inquiry deleted');loadInquiries()};
  const exportCsv=()=>{const rows=[['Name','Email','Phone','Service','Status','Priority','Created'],...inquiries.map(i=>[i.name,i.email,i.phone,i.service,i.status,i.priority,i.createdAt])];const csv=rows.map(r=>r.map(v=>`"${String(v??'').replaceAll('"','""')}"`).join(',')).join('\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));const a=document.createElement('a');a.href=url;a.download=`sites-maker-inquiries-${new Date().toISOString().slice(0,10)}.csv`;a.click();URL.revokeObjectURL(url)};
  const saveReview=async(payload,id)=>{const d=await api(id?`/api/reviews/${id}`:'/api/reviews',{method:id?'PATCH':'POST',body:JSON.stringify(payload)},token);setReviews(x=>id?x.map(r=>r._id===id?d.data:r):[d.data,...x]);setToast('Review saved')};
  const deleteReview=async id=>{if(!confirm('Delete this review?'))return;await api(`/api/reviews/${id}`,{method:'DELETE'},token);setReviews(x=>x.filter(r=>r._id!==id));setToast('Review deleted')};
  return <div className="admin-shell"><aside className="sidebar"><div className="brand-mark side"><img src="/assets/sites-maker-logo.webp" alt="Sites Maker" className="brand-logo"/><div><b>Sites</b> <em>Maker</em><small>ADMIN CONSOLE</small></div></div><nav>{[['overview','⌂','Overview'],['inquiries','◈',`Inquiries ${stats.new?`(${stats.new})`:''}`],['customers','◎','Customers'],['analytics','◌','Analytics'],['reviews','☆','Reviews'],['quotes','▣','Quote builder'],['clients','♙','Client portal']].map(([id,ic,l])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}><span>{ic}</span>{l}</button>)}</nav><div className="side-bottom"><div className="health"><i/> API online<div><small>MongoDB + protected API</small><strong>Healthy</strong></div></div><button onClick={logout} className="logout">↪ Sign out</button></div></aside>
  <main className="admin-main"><header className="topbar"><div><span className="eyebrow">Command center</span><h1>{({overview:'Good to see you.',inquiries:'Customer enquiries',customers:'Customers',analytics:'Analytics',reviews:'Reviews',quotes:'Quote builder',clients:'Client portal'})[tab]}</h1></div><div className="top-actions"><div className="live-status"><i/> Live <small>{lastSync?`Synced ${lastSync.toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}`:'Syncing'}</small></div><button className="icon-btn" onClick={()=>{loadInquiries();loadExtra()}}>↻</button><button className="export-btn" onClick={exportCsv}>↓ Export CSV</button></div></header>{error&&<div className="panel-error">{error}<button onClick={()=>setError('')}>×</button></div>}
  {tab==='overview'&&<Overview stats={stats} analytics={analytics} inquiries={inquiries} onOpen={setSelected}/>} 
  {tab==='inquiries'&&<InquiryTable inquiries={inquiries} loading={loading} query={query} setQuery={setQuery} status={status} setStatus={setStatus} priority={priority} setPriority={setPriority} selected={selected} setSelected={setSelected}/>} 
  {tab==='customers'&&<Customers data={customers} onOpen={email=>{const i=inquiries.find(x=>x.email===email);if(i)setSelected(i);else setTab('inquiries')}}/>}
  {tab==='analytics'&&<Analytics data={analytics}/>} 
  {tab==='reviews'&&<Reviews reviews={reviews} onSave={saveReview} onDelete={deleteReview}/>} 
  {tab==='quotes'&&<QuoteBuilder onCreate={()=>setToast('Quote ready to print or save as PDF')}/>}
  {tab==='clients'&&<ClientManager clients={clients} token={token} onChange={loadExtra} onToast={setToast}/> } 
  </main>{selected&&<DetailDrawer inquiry={selected} onClose={()=>setSelected(null)} onUpdate={update} onReply={()=>setReplyOpen(true)} onDelete={()=>remove(selected._id)}/>} {replyOpen&&selected&&<ReplyModal inquiry={selected} token={token} onClose={()=>setReplyOpen(false)} onSent={d=>{setSelected(d);setInquiries(x=>x.map(i=>i._id===d._id?d:i));setReplyOpen(false);setToast('Reply sent')}}/>}{toast&&<div className="admin-toast">✓ {toast}</div>}</div>
}

function Overview({stats,analytics,inquiries,onOpen}){return <><section className="stat-grid"><Stat label="Total enquiries" value={stats.total||0} icon="◈" trend="All time"/><Stat label="New leads" value={stats.new||0} icon="✦" tone="violet" trend="Need attention"/><Stat label="In progress" value={stats.inProgress||0} icon="⌁" tone="gold" trend="Active pipeline"/><Stat label="Completed" value={stats.completed||0} icon="✓" tone="green" trend="Closed wins"/></section><div className="overview-grid"><section className="workspace-card"><div className="workspace-head"><div><h2>Recent enquiries</h2><p>Latest customer activity.</p></div></div><div className="mini-list">{inquiries.slice(0,6).map(i=><button key={i._id} onClick={()=>onOpen(i)}><span className="avatar">{i.name?.[0]?.toUpperCase()}</span><span><strong>{i.name}</strong><small>{i.service} · {fmtDate(i.createdAt)}</small></span><Badge value={i.status}/></button>)}{!inquiries.length&&<div className="empty">No enquiries yet.</div>}</div></section><section className="workspace-card"><div className="workspace-head"><div><h2>Conversion pulse</h2><p>Last 30 days</p></div></div><div className="big-number">{analytics?.last30Days||0}</div><p className="muted">tracked website events</p><div className="bar-stack">{(analytics?.events||[]).slice(0,5).map(x=><div key={x._id}><span>{x._id}</span><b><i style={{width:`${Math.min(100,x.count*8)}%`}}/></b><em>{x.count}</em></div>)}</div></section></div></>}
function Stat({label,value,icon,trend,tone=''}){return <div className={`stat-card ${tone}`}><div className="stat-icon">{icon}</div><div><span>{label}</span><strong>{value}</strong><small>{trend}</small></div><div className="spark"><i/><i/><i/><i/><i/></div></div>}
function InquiryTable({inquiries,loading,query,setQuery,status,setStatus,priority,setPriority,selected,setSelected}){return <section className="workspace-card"><div className="workspace-head"><div><h2>Customer enquiries</h2><p>Search, triage and open any lead.</p></div><div className="filters"><div className="search"><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search name, email, service…"/></div><select value={status} onChange={e=>setStatus(e.target.value)}><option value="">All statuses</option>{Object.entries(statusMeta).map(([v,[l]])=><option key={v} value={v}>{l}</option>)}</select><select value={priority} onChange={e=>setPriority(e.target.value)}><option value="">All priorities</option>{Object.keys(priorityMeta).map(v=><option key={v} value={v}>{priorityMeta[v]}</option>)}</select></div></div><div className="table-wrap"><table><thead><tr><th>Customer</th><th>Service</th><th>Status</th><th>Priority</th><th>Received</th><th/></tr></thead><tbody>{loading&&!inquiries.length?<tr><td colSpan="6"><div className="loading"><span/> Loading…</div></td></tr>:inquiries.length?inquiries.map(i=><tr key={i._id} onClick={()=>setSelected(i)} className={selected?._id===i._id?'selected':''}><td><div className="customer-cell"><div className="avatar">{i.name?.[0]?.toUpperCase()}</div><div><strong>{i.name}</strong><small>{i.email}</small></div></div></td><td><span className="service-pill">{i.service||'Other'}</span></td><td><Badge value={i.status}/></td><td><Badge type="priority" value={i.priority||'normal'}/></td><td className="date">{fmtDate(i.createdAt)}</td><td>→</td></tr>):<tr><td colSpan="6"><div className="empty"><h3>No enquiries found</h3><p>Try another filter.</p></div></td></tr>}</tbody></table></div></section>}
function Customers({data,onOpen}){return <section className="workspace-card"><div className="workspace-head"><div><h2>Customer directory</h2><p>Grouped by email so repeat enquiries stay together.</p></div></div><div className="customer-grid">{data.map(c=><button key={c._id} onClick={()=>onOpen(c.email)}><div className="avatar">{c.name?.[0]?.toUpperCase()}</div><strong>{c.name}</strong><span>{c.email}</span><small>{c.phone}</small><b>{c.enquiries} {c.enquiries===1?'enquiry':'enquiries'}</b></button>)}{!data.length&&<div className="empty">No customers yet.</div>}</div></section>}
function Analytics({data}){return <div className="analytics-grid"><section className="workspace-card"><h2>Devices</h2>{(data?.devices||[]).map(x=><div className="metric-row" key={x._id}><span>{x._id}</span><b>{x.count}</b></div>)}</section><section className="workspace-card"><h2>Top pages</h2>{(data?.paths||[]).map(x=><div className="metric-row" key={x._id}><span>{x._id}</span><b>{x.count}</b></div>)}</section><section className="workspace-card"><h2>Top events</h2>{(data?.events||[]).map(x=><div className="metric-row" key={x._id}><span>{x._id}</span><b>{x.count}</b></div>)}</section></div>}
function Reviews({reviews,onSave,onDelete}){const[editing,setEditing]=useState(null);const[name,setName]=useState(''),[role,setRole]=useState('Client'),[rating,setRating]=useState(5),[text,setText]=useState(''),[approved,setApproved]=useState(false);const reset=()=>{setEditing(null);setName('');setRole('Client');setRating(5);setText('');setApproved(false)};const edit=r=>{setEditing(r._id);setName(r.name);setRole(r.role);setRating(r.rating);setText(r.text);setApproved(r.approved)};return <div className="reviews-layout"><section className="workspace-card"><div className="workspace-head"><div><h2>{editing?'Edit review':'Add review'}</h2><p>Only approved reviews appear publicly.</p></div></div><div className="form-grid"><label>Name<input value={name} onChange={e=>setName(e.target.value)}/></label><label>Role<input value={role} onChange={e=>setRole(e.target.value)}/></label><label>Rating<select value={rating} onChange={e=>setRating(+e.target.value)}>{[5,4,3,2,1].map(x=><option key={x}>{x}</option>)}</select></label><label className="checkline"><input type="checkbox" checked={approved} onChange={e=>setApproved(e.target.checked)}/> Approved</label><label className="full">Review<textarea rows="6" value={text} onChange={e=>setText(e.target.value)}/></label></div><button className="primary-btn" onClick={async()=>{await onSave({name,role,rating,text,approved},editing);reset()}}>{editing?'Update review':'Create review'}</button>{editing&&<button className="secondary-btn" onClick={reset}>Cancel</button>}</section><section className="workspace-card"><h2>Review library</h2><div className="review-admin-list">{reviews.map(r=><article key={r._id}><div><strong>{r.name}</strong><small>{r.role} · {'★'.repeat(r.rating)}</small></div><span className={r.approved?'approved':'pending'}>{r.approved?'Published':'Draft'}</span><p>{r.text}</p><div><button className="secondary-btn" onClick={()=>edit(r)}>Edit</button><button className="danger-btn" onClick={()=>onDelete(r._id)}>Delete</button></div></article>)}</div></section></div>}
function QuoteBuilder(){const[name,setName]=useState(''),[email,setEmail]=useState(''),[type,setType]=useState('Business website'),[pages,setPages]=useState(5),[admin,setAdmin]=useState(true),[payment,setPayment]=useState(false),[seo,setSeo]=useState(true),[deploy,setDeploy]=useState(true),[domain,setDomain]=useState(false);const base={'Business website':18000,'Portfolio / personal brand':26000,'E-commerce website':35000,'Custom web application':42000};const total=base[type]+Math.max(0,pages-5)*1800+(admin?6000:0)+(payment?7000:0)+(seo?4000:0)+(deploy?3000:0)+(domain?2500:0);const print=()=>window.print();return <section className="workspace-card quote-builder"><div className="quote-form"><span className="eyebrow">Professional quotation</span><h2>Build a client quote</h2><div className="form-grid"><label>Client name<input value={name} onChange={e=>setName(e.target.value)} placeholder="Client name"/></label><label>Client email<input value={email} onChange={e=>setEmail(e.target.value)} placeholder="client@email.com"/></label><label>Website type<select value={type} onChange={e=>setType(e.target.value)}>{Object.keys(base).map(x=><option key={x}>{x}</option>)}</select></label><label>Pages<input type="number" min="1" max="50" value={pages} onChange={e=>setPages(+e.target.value||1)}/></label></div><div className="check-list"><label><input type="checkbox" checked={admin} onChange={e=>setAdmin(e.target.checked)}/> Admin panel +₹6k</label><label><input type="checkbox" checked={payment} onChange={e=>setPayment(e.target.checked)}/> Payment gateway +₹7k</label><label><input type="checkbox" checked={seo} onChange={e=>setSeo(e.target.checked)}/> SEO setup +₹4k</label><label><input type="checkbox" checked={deploy} onChange={e=>setDeploy(e.target.checked)}/> Deployment +₹3k</label><label><input type="checkbox" checked={domain} onChange={e=>setDomain(e.target.checked)}/> Domain setup +₹2.5k</label></div><button className="primary-btn" onClick={print}>Print / Save PDF</button></div><div className="quote-preview" id="quotePrintable"><div className="quote-brand">W <span>WEBSITE MAKERS</span></div><small>PROFESSIONAL WEBSITE QUOTATION</small><h2>{name||'Your Client'}</h2><p>{email||'client@email.com'}</p><hr/><div className="quote-line"><span>{type}</span><b>{money(base[type])}</b></div><div className="quote-line"><span>{pages} pages</span><b>{money(Math.max(0,pages-5)*1800)}</b></div>{admin&&<div className="quote-line"><span>Admin panel</span><b>₹6,000</b></div>}{payment&&<div className="quote-line"><span>Payment gateway</span><b>₹7,000</b></div>}{seo&&<div className="quote-line"><span>SEO setup</span><b>₹4,000</b></div>}{deploy&&<div className="quote-line"><span>Deployment</span><b>₹3,000</b></div>}{domain&&<div className="quote-line"><span>Domain setup</span><b>₹2,500</b></div>}<div className="quote-total"><span>Estimated total</span><strong>{money(total)}</strong></div><small>Scope-based estimate · final price confirmed after requirements.</small></div></section>}

function ClientManager({clients,token,onChange,onToast}){const[name,setName]=useState(''),[email,setEmail]=useState(''),[phone,setPhone]=useState(''),[password,setPassword]=useState(''),[project,setProject]=useState(''),[progress,setProgress]=useState(0),[liveUrl,setLiveUrl]=useState(''),[selected,setSelected]=useState('');const create=async()=>{try{const d=await api('/api/clients/admin',{method:'POST',body:JSON.stringify({name,email,phone,password})},token);onToast('Client created');setSelected(d.data._id);setName('');setEmail('');setPhone('');setPassword('');await onChange()}catch(e){onToast(e.message)}};const addProject=async()=>{if(!selected||!project)return;try{await api(`/api/clients/admin/${selected}/projects`,{method:'POST',body:JSON.stringify({name:project,progress:Number(progress),liveUrl,milestones:[{label:'Discovery & requirements',done:Number(progress)>=20},{label:'Design',done:Number(progress)>=45},{label:'Development',done:Number(progress)>=70},{label:'Testing & launch',done:Number(progress)>=100}]})},token);onToast('Project assigned');setProject('');setLiveUrl('');await onChange()}catch(e){onToast(e.message)}};return <div className="client-manager"><section className="workspace-card"><div className="workspace-head"><div><h2>Create client</h2><p>Give a client secure portal credentials.</p></div></div><div className="form-grid"><label>Name<input value={name} onChange={e=>setName(e.target.value)}/></label><label>Email<input value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Phone<input value={phone} onChange={e=>setPhone(e.target.value)}/></label><label>Password (8+ chars)<input type="password" value={password} onChange={e=>setPassword(e.target.value)}/></label></div><button className="primary-btn" onClick={create}>Create secure client ↗</button></section><section className="workspace-card"><h2>Assign project</h2><div className="form-grid"><label>Client<select value={selected} onChange={e=>setSelected(e.target.value)}><option value="">Select client</option>{clients.map(c=><option key={c._id} value={c._id}>{c.name} · {c.email}</option>)}</select></label><label>Project name<input value={project} onChange={e=>setProject(e.target.value)} placeholder="Website redesign"/></label><label>Progress %<input type="number" min="0" max="100" value={progress} onChange={e=>setProgress(e.target.value)}/></label><label>Live URL<input value={liveUrl} onChange={e=>setLiveUrl(e.target.value)} placeholder="https://..."/></label></div><button className="primary-btn" onClick={addProject} disabled={!selected}>Assign project ↗</button></section><section className="workspace-card"><h2>Client accounts</h2><div className="customer-grid">{clients.map(c=><button key={c._id} onClick={()=>setSelected(c._id)}><div className="avatar">{c.name?.[0]?.toUpperCase()}</div><strong>{c.name}</strong><span>{c.email}</span><small>{c.projects?.length||0} project(s)</small></button>)}</div></section></div>}

function DetailDrawer({inquiry,onClose,onUpdate,onReply,onDelete}){const[notes,setNotes]=useState(inquiry.adminNotes||'');const[saving,setSaving]=useState(false);useEffect(()=>setNotes(inquiry.adminNotes||''),[inquiry._id,inquiry.adminNotes]);return <div className="drawer-layer"><div className="drawer-backdrop" onClick={onClose}/><aside className="drawer"><div className="drawer-head"><div><span className="eyebrow">Inquiry #{String(inquiry._id).slice(-6).toUpperCase()}</span><h2>{inquiry.name}</h2><p>{inquiry.email}</p></div><button className="icon-btn" onClick={onClose}>×</button></div><div className="drawer-actions"><button className="primary-btn small" onClick={onReply}>↗ Respond</button><a className="secondary-btn" href={`tel:${inquiry.phone}`}>☎ Call</a><a className="secondary-btn" href={`https://wa.me/${inquiry.phone.replace(/\D/g,'')}`} target="_blank" rel="noreferrer">WhatsApp</a></div><div className="drawer-section"><label>Status</label><div className="segmented">{Object.entries(statusMeta).map(([v,[l]])=><button key={v} className={inquiry.status===v?'active':''} onClick={()=>onUpdate(inquiry._id,{status:v})}>{l}</button>)}</div></div><div className="drawer-section two"><div><label>Priority</label><select value={inquiry.priority||'normal'} onChange={e=>onUpdate(inquiry._id,{priority:e.target.value})}>{Object.keys(priorityMeta).map(v=><option key={v} value={v}>{priorityMeta[v]}</option>)}</select></div><div><label>Service</label><div className="read-field">{inquiry.service||'Other'}</div></div></div><div className="message-box"><label>Customer message</label><p>{inquiry.message||'No message supplied.'}</p></div><div className="drawer-section"><label>Private notes</label><textarea value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Budget, requirements, follow-up…"/><button className="save-note" disabled={saving} onClick={async()=>{setSaving(true);try{await onUpdate(inquiry._id,{adminNotes:notes})}finally{setSaving(false)}}}>{saving?'Saving…':'Save notes'}</button></div>{inquiry.responses?.length>0&&<div className="timeline"><label>Conversation</label>{inquiry.responses.map((r,i)=><div className="timeline-item" key={i}><i/><div><small>{fmtDate(r.sentAt)} · {r.channel}</small><p>{r.message}</p></div></div>)}</div>}<div className="drawer-footer"><span>{inquiry.phone}</span><button className="danger-btn" onClick={onDelete}>Delete inquiry</button></div></aside></div>}
function ReplyModal({inquiry,token,onClose,onSent}){const[subject,setSubject]=useState('Re: Your Website Makers enquiry'),[message,setMessage]=useState(`Hi ${inquiry.name},\n\nThank you for reaching out to Website Makers.\n\n`),[busy,setBusy]=useState(false),[error,setError]=useState('');const send=async()=>{setBusy(true);setError('');try{const d=await api(`/api/inquiries/${inquiry._id}/respond`,{method:'POST',body:JSON.stringify({subject,message})},token);onSent(d.data)}catch(e){setError(e.message)}finally{setBusy(false)}};return <div className="modal-layer"><div className="modal-backdrop" onClick={onClose}/><div className="reply-modal"><div className="reply-head"><div><span className="eyebrow">Direct email</span><h2>Reply to {inquiry.name}</h2><p>{inquiry.email}</p></div><button className="icon-btn" onClick={onClose}>×</button></div><label>Subject<input value={subject} onChange={e=>setSubject(e.target.value)}/></label><label>Message<textarea rows="10" value={message} onChange={e=>setMessage(e.target.value)}/></label>{error&&<div className="panel-error">{error}</div>}<div className="reply-footer"><span>SMTP reply + conversation history</span><button className="primary-btn" onClick={send} disabled={busy}>{busy?'Sending…':'Send reply ↗'}</button></div></div></div>}
