import { useEffect, useState } from 'react';
import './admin.css';
const API=(import.meta.env.VITE_API_BASE_URL||(import.meta.env.PROD?'https://website-makers-api.onrender.com':'http://localhost:4000')).replace(/\/$/,'');
const KEY='wm_client_token';
export default function ClientPortal(){const[token,setToken]=useState(()=>sessionStorage.getItem(KEY));if(!token)return <PortalLogin onLogin={t=>{sessionStorage.setItem(KEY,t);setToken(t)}}/>;return <PortalHome token={token} onLogout={()=>{sessionStorage.removeItem(KEY);setToken(null)}}/>}
function BrandLockup({subtitle='CLIENT PORTAL'}){return <div className="brand-lockup"><span className="brand-logo-wrap"><img src="/assets/sites-maker-logo.png" alt="Sites Maker logo"/></span><span className="brand-wordmark"><b>Sites</b> <em>Maker</em><small>{subtitle}</small></span></div>}

function PortalLogin({onLogin}){const[email,setEmail]=useState(''),[password,setPassword]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);return <div className="admin-auth"><div className="login-card"><BrandLockup subtitle="CLIENT PORTAL" /><div className="login-copy"><span className="eyebrow">Private project space</span><h1>Your project, visible.</h1><p>Check milestones, progress and live links without chasing messages.</p></div><form onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{const r=await fetch(`${API}/api/clients/login`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,password})});const d=await r.json();if(!r.ok)throw Error(d.error||'Login failed');onLogin(d.token)}catch(e){setError(e.message)}finally{setBusy(false)}}}><label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></label><label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} required/></label>{error&&<div className="auth-error">{error}</div>}<button className="primary-btn" disabled={busy}>{busy?'Checking…':'Open my portal ↗'}</button></form></div></div>}
function PortalHome({token,onLogout}){const[data,setData]=useState(null),[error,setError]=useState('');useEffect(()=>{fetch(`${API}/api/clients/me`,{headers:{Authorization:`Bearer ${token}`}}).then(async r=>{const d=await r.json();if(!r.ok)throw Error(d.error||'Session expired');setData(d.data)}).catch(e=>{setError(e.message);onLogout()})},[token]);if(!data)return <div className="admin-auth"><div className="login-card"><h2>Loading project space…</h2>{error&&<p>{error}</p>}</div></div>;return <div className="admin-shell"><main className="admin-main portal-main"><header className="topbar"><div><span className="eyebrow">Client portal</span><h1>Welcome, {data.name}.</h1></div><button className="secondary-btn" onClick={onLogout}>Sign out</button></header><div className="portal-grid">{data.projects.map(p=><section className="workspace-card" key={p._id}><span className="eyebrow">Project</span><h2>{p.name}</h2><div className="portal-progress"><div><span>{p.status.replace('-', ' ')}</span><b>{p.progress}%</b></div><i><em style={{width:`${p.progress}%`}}/></i></div><div className="milestones">{p.milestones.map((m,i)=><div key={i} className={m.done?'done':''}><span>{m.done?'✓':'○'}</span>{m.label}</div>)}</div>{p.liveUrl&&<a className="primary-btn" href={p.liveUrl} target="_blank" rel="noreferrer">Open live project ↗</a>}</section>)}{!data.projects.length&&<section className="workspace-card"><h2>No project assigned yet.</h2><p>Your project workspace will appear here when Sites Maker adds it.</p></section>}</div></main></div>}
